### ISSUE TITLE
第二章【在训练集上训练和评估】中部分代码有误

### ISSUE THREAD

**Issue by lifangzheng** [apachecn/hands_on_Ml_with_Sklearn_and_TF#44]
# 在训练集上训练和评估

> 行的通，尽管预测并不怎么准确（比如，第二个预测偏离了 50%！）。让我们使用 Scikit-Learn 的mean_squared_error函数，用全部训练集来计算下这个回归模型的 RMSE：
> 
> from sklearn.metrics import mean_squared_error
> housing_predictions = lin_reg.predict(housing_prepared)
> lin_mse = mean_squared_error(housing_labels, housing_predictions)

**最后一行应为lin_mse = mean_squared_error(some_labels, housing_predictions)**

**Comment by wizardforcel** [comment]
fixed
